CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  password VARCHAR (50)
);

CREATE TABLE MetasVen (
  id INT PRIMARY KEY AUTO_INCREMENT,
  codven VARCHAR(255) NOT NULL,
  dtmeta DATE NOT NULL,
  meta VARCHAR(255)
);